"""
==================================================
REETA — automation/workflow_engine.py
==================================================
PURPOSE:
    Executes a sequence of automation steps generated by the CommandParser.
    Hardened with fail-fast execution and state tracking.
==================================================
"""

from utils.logger import get_logger
from automation.app_control import AppController
from automation.browser_control import BrowserController
from automation.file_manager import FileManager
from automation.keyboard_mouse import InputController
from automation.retry_manager import AutomationRetryException
from automation.calendar_manager import CalendarManager
from automation.communications import CommunicationsManager
from automation.vision_manager import VisionManager

logger = get_logger(__name__)

class WorkflowEngine:
    """Executes discrete JSON automation steps sequentially with fail-fast safety."""

    def __init__(self):
        self.app_ctrl = AppController()
        self.browser_ctrl = BrowserController()
        self.file_ctrl = FileManager()
        self.input_ctrl = InputController()
        self.calendar_ctrl = CalendarManager()
        self.comms_ctrl = CommunicationsManager()
        self.vision_ctrl = VisionManager()

    def execute_steps(self, steps: list[dict]) -> str:
        """
        Runs the parsed steps.
        If any step fails, execution halts immediately (Fail-Fast).
        """
        if not steps:
            return "I couldn't figure out how to do that."

        executed_actions = []

        for index, step in enumerate(steps):
            action = step.get("action")
            target = step.get("target", "")

            logger.info(f"Executing workflow step {index + 1}/{len(steps)}: {action} -> {target}")

            try:
                if action == "open_app":
                    result = self.app_ctrl.open_application(target)
                elif action == "close_app":
                    result = self.app_ctrl.close_application(target)
                elif action == "web_search":
                    result = self.browser_ctrl.search_google(target)
                elif action == "open_url":
                    result = self.browser_ctrl.open_website(target)
                elif action == "create_folder":
                    result = self.file_ctrl.create_folder(target)
                elif action == "delete_file":
                    # Hardcoded to require confirmation in stabilized build
                    result = self.file_ctrl.delete_file(target, confirmed=False)
                    if "CONFIRM_REQUIRED" in result:
                        logger.warning(f"Workflow halted: Confirmation required to delete {target}")
                        return f"Workflow paused. Please confirm you want to delete {target}."
                elif action == "type_text":
                    result = self.input_ctrl.type_text(target)
                elif action == "press_key":
                    keys = target.split('+')
                    result = self.input_ctrl.press_shortcut(*keys)
                elif action == "add_calendar_event":
                    result = self.calendar_ctrl.add_event(target)
                elif action == "read_reminders":
                    result = self.calendar_ctrl.read_reminders()
                elif action == "send_message":
                    result = self.comms_ctrl.send_message(target)
                elif action == "scan_document":
                    result = self.vision_ctrl.scan_document(target)
                else:
                    logger.warning(f"Unknown action: {action}")
                    return f"Workflow failed: I don't know how to execute the '{action}' command."
                
                # Check for explicit failure strings
                if result and "Failed" in result:
                    logger.error(f"Step {index + 1} failed: {result}. Halting workflow.")
                    return f"Workflow failed at step {index + 1} during {action}."
                    
                executed_actions.append(action)

            except AutomationRetryException as e:
                logger.error(f"Permanent failure during step {index + 1}: {e}")
                return f"Workflow failed at step {index + 1} due to a timeout or missing element."
            except Exception as e:
                logger.error(f"Unexpected error during step {index + 1}: {e}", exc_info=True)
                return f"Workflow crashed at step {index + 1}."

        return f"Successfully executed workflow with {len(executed_actions)} steps."
