"""
==================================================
REETA — orchestration/state.py
==================================================
PURPOSE:
    Defines the global GraphState for LangGraph.
    This state object is passed to every agent during workflow execution.
==================================================
"""

from typing import TypedDict, List, Dict, Any, Annotated
import operator

# Reducer functions for LangGraph state management
# We use operator.add to append items to lists rather than overwriting them

class GraphState(TypedDict):
    """
    The shared state of the multi-agent system.
    Agents read from this state and return updates to it.
    """
    user_request: str                   # The original task from the user
    current_agent: str                  # The agent currently executing
    
    # We use Annotated[List, operator.add] so that when an agent returns 
    # {'messages': [new_msg]}, LangGraph appends it instead of replacing the list.
    messages: Annotated[List[dict], operator.add]  
    
    # A shared dictionary for passing structured data (e.g. parsed URLs, code snippets)
    shared_context: dict                
    
    # The sequence of tasks generated by the PlanningAgent
    task_plan: List[dict]               
    
    # The final output to be sent to the user
    final_response: str                 
    
    # Error tracking for recovery loops
    errors: Annotated[List[str], operator.add]
